version: "3.9"

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    # command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
