AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Sample SAM Template for app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CreateToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: create.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Create:
          Type: Api
          Properties:
            Path: /todo
            Method: post

  GetToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: get.lambdaHandler
      Runtime: nodejs16.x
      Events:
        Get:
          Type: Api
          Properties:
            Path: /todo
            Method: get

  GetCompleteToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: getComplete.lambdaHandler
      Runtime: nodejs16.x
      Events:
        Get:
          Type: Api
          Properties:
            Path: /todo/complete
            Method: Get

  GetSpecificToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: getSpecific.lambdaHandler
      Runtime: nodejs16.x
      Events:
        Get:
          Type: Api
          Properties:
            Path: /todo/{id}
            Method: get

  CompleteToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todo/
      Handler: complete.lambdaHandler
      Runtime: nodejs16.x
      Events:
        Update:
          Type: Api
          Properties:
            Path: /todo/{id}/complete
            Method: patch
